function createfigure(ZData1, YData1, XData1, XData2, YData2, ZData2, VertexNormals1, YData3, XData3, Vertices1, Faces1, FaceVertexCData1, Z1)
%CREATEFIGURE(ZDATA1,YDATA1,XDATA1,XDATA2,YDATA2,ZDATA2,VERTEXNORMALS1,YDATA3,XDATA3,VERTICES1,FACES1,FACEVERTEXCDATA1,Z1)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  ZDATA2:  line zdata
%  VERTEXNORMALS1:  patch vertexnormals
%  YDATA3:  patch ydata
%  XDATA3:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  Z1:  stem3 z

%  Auto-generated by MATLAB on 23-Jan-2013 18:06:53

% Create figure
figure1 = figure('Name','untitled fit 1');

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[3145728 157974664]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.010956 0.122445]);
view(subplot1,[-37.5 30]);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'all');

% Create surface
surface('Parent',subplot1,'Tag','curvefit.FunctionSurface','ZData',ZData1,...
    'YData',YData1,...
    'XData',XData1,...
    'DisplayName','untitled fit 1',...
    'CData',ZData1);

% Create line
line(XData2,YData2,ZData2,'Parent',subplot1,'MarkerFaceColor',[0 0 1],...
    'MarkerEdgeColor',[1 1 1],...
    'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 1],...
    'DisplayName','z vs. x, y');

% Create xlabel
xlabel('x','Fontsize',16);

% Create ylabel
ylabel('y','Fontsize',16);

% Create zlabel
zlabel('z','Fontsize 2');

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Location','NorthEast');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[3145728 157974664]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.010956 0.122445]);
view(subplot2,[90 -0]);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'all');

% Create patch
patch('Parent',subplot2,'VertexNormals',VertexNormals1,'YData',YData3,...
    'XData',XData3,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor',[0.2 0.2 0.2],...
    'FaceAlpha',0.2,...
    'FaceVertexCData',FaceVertexCData1,...
    'CData',FaceVertexCData1);

% Create stem3
stem3(XData2,YData2,Z1,'MarkerFaceColor','auto','Parent',subplot2,...
    'DisplayName','untitled fit 1 - residuals');

% Create xlabel
xlabel('x','Visible','off','HorizontalAlignment','center','Fontsize',16);

% Create ylabel
ylabel('y','VerticalAlignment','cap','HorizontalAlignment','center','Fontsize',16);

% Create zlabel
zlabel('z','Fontsize',16);

% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Location','NorthEast');

