function [] = set_path_2_win()
% warning('off');
% addpath('U:\PhD\matlab\kpc\');
% addpath('U:\PhD\matlab\kpc\kde2d\');
% addpath('Z:\\knowgraph_data\test4var.dir\scripts.dir\');
% addpath('Z:\\KCI\version10102013\KCI-test\');
% addpath('Z:\\KCI\version10102013\KCI-test\algorithms\');
% addpath('Z:\\KCI\version10102013\KCI-test\CI_PERM\');
% addpath('Z:\\KCI\version10102013\KCI-test\exp\');
% addpath('Z:\\KCI\version10102013\KCI-test\gpml-matlab\gpml\');
% addpath('U:\PhD\matlab\bnt\BNT\general\');
% addpath('U:\PhD\matlab\bnt\BNT\inference\');
% addpath('U:\PhD\matlab\bnt\BNT\learning');  
% addpath('U:\PhD\matlab\bnt\BNT\potentials');
% addpath('U:\PhD\matlab\bnt\KPMstats\CVS\');
% addpath('U:\PhD\matlab\bnt\graph\');
% addpath('U:\PhD\matlab\bnt\GraphViz\');
% addpath('U:\PhD\matlab\bnt\');
% addpath('U:\PhD\matlab\bnt\KPMstats\CVS\');
% addpath('U:\PhD\matlab\bnt\KPMstats\');
% addpath('U:\PhD\matlab\bnt\KPMtools\');
% addpath('Z:\pchsicparallelizesubtests.dir\matpy1.dir\');
% addpath('U:\PhD\matlab\kpc\Backdoorcriterioncopula1d');
% addpath('U:\PhD\matlab\kpc\Backdoorcriterioncopula2d');
% addpath('U:\PhD\matlab\kpc\Backdoorcriterioncopula2d_method2');

warning('off');
addpath('U:\PhD\matlab\kpc\kde2d\');
addpath('U:\PhD\matlab\kpc\');
addpath('U:\PhD\matlab\bnt\BNT\general\');
addpath('U:\PhD\matlab\bnt\BNT\inference\');
addpath('U:\PhD\matlab\bnt\BNT\learning');  
addpath('U:\PhD\matlab\bnt\BNT\potentials');
addpath('U:\PhD\matlab\bnt\KPMstats\CVS\');
addpath('U:\PhD\matlab\bnt\graph\');
addpath('U:\PhD\matlab\bnt\GraphViz\');
addpath('U:\PhD\matlab\bnt\');
addpath('U:\PhD\matlab\bnt\KPMstats\CVS\');
addpath('U:\PhD\matlab\bnt\KPMstats\');
addpath('U:\PhD\matlab\bnt\KPMtools\');
addpath('U:\PhD\matlab\KCI\version10102013\KCI-test');
addpath('U:\PhD\matlab\KCI\version10102013\KCI-test\algorithms\');
addpath('U:\PhD\matlab\KCI\version10102013\KCI-test\CI_PERM\');
addpath('U:\PhD\matlab\KCI\version10102013\KCI-test\exp\');
addpath('U:\PhD\matlab\KCI\version10102013\KCI-test\gpml-matlab\gpml\');
addpath('\datas\xlan\hours\pchsicparallelizesubtests.dir\matpy1.dir\');
addpath('\datas\xlan\hours\knowgraph_data\test4var.dir\scripts.dir\');
